"use client";

import { useMemo, useRef, useState } from "react";
import type { Article, MediaItem, Revision, WikiProject, WikiSettings } from "../lib/types";
import { exportProject, importProject, putRecord, uid, validateProject } from "../lib/db";
import { parseWiki, sourceToPlainText } from "../lib/wiki";
import { Field } from "./Modal";

function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function download(name: string, content: BlobPart, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.style.display = "none"; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: React.ReactNode }) {
  return <><div className="article-kicker">Special page</div><div className="article-title-row"><div><h1>{title}</h1>{description && <p className="description">{description}</p>}</div>{actions}</div></>;
}

export function AllArticles({ articles, onOpen, onCreate, onRename, onDuplicate, onDelete }: { articles: Article[]; onOpen: (article: Article) => void; onCreate: () => void; onRename: (article: Article) => void; onDuplicate: (article: Article) => void; onDelete: (article: Article) => void }) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<"title" | "modified" | "created" | "size">("title"); const [selected, setSelected] = useState<string[]>([]);
  const visible = useMemo(() => articles.filter((article) => !article.trashedAt && (!query || `${article.title} ${article.description} ${article.categories.join(" ")}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "modified" ? b.modifiedAt.localeCompare(a.modifiedAt) : sort === "created" ? b.createdAt.localeCompare(a.createdAt) : b.source.length - a.source.length), [articles, query, sort]);
  const exportSelected = () => { const chosen = articles.filter((article) => selected.includes(article.id)); download("cockipedia-articles.json", JSON.stringify({ format: "cockipedia-articles", version: 1, articles: chosen }, null, 2), "application/json"); };
  return <div><PageHeader title="All articles" description={`${visible.length} page${visible.length === 1 ? "" : "s"} in your personal encyclopedia`} actions={<button className="primary" onClick={onCreate}>＋ Create article</button>} />
    <div className="management-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter articles" aria-label="Filter articles" /><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)} aria-label="Sort articles"><option value="title">Title (A–Z)</option><option value="modified">Recently edited</option><option value="created">Date created</option><option value="size">Article size</option></select><button disabled={!selected.length} onClick={exportSelected}>Export selected ({selected.length})</button></div>
    <div className="table-scroll"><table className="wikitable management-table"><thead><tr><th><input type="checkbox" aria-label="Select all" checked={visible.length > 0 && selected.length === visible.length} onChange={(event) => setSelected(event.target.checked ? visible.map((article) => article.id) : [])} /></th><th>Title</th><th>Categories</th><th>Last edited</th><th>Size</th><th>Actions</th></tr></thead><tbody>{visible.map((article) => <tr key={article.id}><td><input type="checkbox" aria-label={`Select ${article.title}`} checked={selected.includes(article.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, article.id] : selected.filter((id) => id !== article.id))} /></td><td><button className="link-button" onClick={() => onOpen(article)}>{article.title}</button><small>{article.description}</small></td><td>{article.categories.join(", ") || "—"}</td><td>{formatDate(article.modifiedAt)}</td><td>{article.source.length.toLocaleString()} B</td><td className="row-actions"><button onClick={() => onRename(article)}>Rename</button><button onClick={() => onDuplicate(article)}>Duplicate</button><button className="danger-text" onClick={() => onDelete(article)}>Delete</button></td></tr>)}</tbody></table></div>
    {!visible.length && <div className="empty-state"><h2>No matching articles</h2><p>Try a different search, or create a new page.</p><button className="primary" onClick={onCreate}>Create article</button></div>}
  </div>;
}

export function CategoryBrowser({ articles, selectedCategory, onSelectCategory, onOpen }: { articles: Article[]; selectedCategory?: string; onSelectCategory: (value?: string) => void; onOpen: (article: Article) => void }) {
  const categories = useMemo(() => { const map = new Map<string, Article[]>(); for (const article of articles.filter((item) => !item.trashedAt)) for (const category of article.categories) map.set(category, [...(map.get(category) ?? []), article]); return [...map.entries()].sort(([a], [b]) => a.localeCompare(b)); }, [articles]);
  const members = selectedCategory ? categories.find(([name]) => name === selectedCategory)?.[1] ?? [] : [];
  return <div><PageHeader title={selectedCategory ? `Category:${selectedCategory}` : "Categories"} description={selectedCategory ? `${members.length} page${members.length === 1 ? "" : "s"} in this category` : "Browse the subjects in your personal encyclopedia"} />{selectedCategory ? <><button className="back-link" onClick={() => onSelectCategory()}>← All categories</button><div className="alphabet-list">{members.map((article) => <button key={article.id} onClick={() => onOpen(article)}><b>{article.title}</b><span>{article.description || sourceToPlainText(article.source).slice(0, 120)}</span></button>)}</div></> : <div className="category-grid">{categories.map(([name, pages]) => <button key={name} onClick={() => onSelectCategory(name)}><b>{name}</b><span>{pages.length} page{pages.length === 1 ? "" : "s"}</span></button>)}</div>}{!categories.length && <div className="empty-state"><h2>No categories yet</h2><p>Add <code>[[Category:Example]]</code> to an article in source mode.</p></div>}</div>;
}

export function MediaLibrary({ media, articles, onChanged }: { media: MediaItem[]; articles: Article[]; onChanged: () => Promise<void> }) {
  const inputRef = useRef<HTMLInputElement>(null); const [busy, setBusy] = useState(false);
  const upload = async (files: FileList | null) => { if (!files?.length) return; setBusy(true); for (const file of Array.from(files)) { if (!file.type.startsWith("image/")) { alert(`${file.name} is not an image.`); continue; } if (file.size > 15 * 1024 * 1024) { alert(`${file.name} is larger than 15 MB.`); continue; } const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); await putRecord<MediaItem>("media", { id: uid("media"), name: file.name, type: file.type, dataUrl, alt: file.name.replace(/\.[^.]+$/, ""), createdAt: new Date().toISOString() }); } await onChanged(); setBusy(false); if (inputRef.current) inputRef.current.value = ""; };
  const remove = async (item: MediaItem) => { const usedBy = articles.filter((article) => article.source.toLocaleLowerCase().includes(`file:${item.name.toLocaleLowerCase()}`)); if (!confirm(`${item.name}${usedBy.length ? ` is used by ${usedBy.length} article(s)` : ""}. Delete it from the media library?`)) return; const { deleteRecord } = await import("../lib/db"); await deleteRecord("media", item.id); await onChanged(); };
  return <div><PageHeader title="Media Library" description="Images are stored locally and can be reused across articles" actions={<><input ref={inputRef} hidden type="file" accept="image/*" multiple onChange={(event) => upload(event.target.files)} /><button className="primary" disabled={busy} onClick={() => inputRef.current?.click()}>{busy ? "Adding…" : "＋ Add images"}</button></>} />
    <div className="media-grid">{media.map((item) => { const usedBy = articles.filter((article) => article.source.toLocaleLowerCase().includes(`file:${item.name.toLocaleLowerCase()}`)); return <figure key={item.id}><div className="media-thumb"><img src={item.dataUrl} alt={item.alt} /></div><figcaption><b>{item.name}</b><span>{usedBy.length ? `Used on ${usedBy.length} page${usedBy.length === 1 ? "" : "s"}` : "Unused"}</span><button onClick={() => navigator.clipboard.writeText(`[[File:${item.name}|thumb|right|260px|${item.alt}]]`)}>Copy wikitext</button><button className="danger-text" onClick={() => remove(item)}>Delete</button></figcaption></figure>; })}</div>
    {!media.length && <div className="empty-state"><div className="empty-icon">▧</div><h2>Your media library is empty</h2><p>Add an image here, then insert it from the visual or source editor.</p><button onClick={() => inputRef.current?.click()}>Choose images</button></div>}
  </div>;
}

export function ImportExportPage({ mode, current, articles, media, onChanged }: { mode: "import" | "export"; current?: Article; articles: Article[]; media: MediaItem[]; onChanged: () => Promise<void> }) {
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [project, setProject] = useState<WikiProject | null>(null); const [error, setError] = useState(""); const [strategy, setStrategy] = useState<"keep" | "overwrite" | "copy">("keep"); const [busy, setBusy] = useState(false);
  const inspect = async (selected: File | null) => { setFile(selected); setProject(null); setError(""); if (!selected) return; try { const text = await selected.text(); if (/\.(txt|wiki|wikitext)$/i.test(selected.name)) return; const parsed: unknown = JSON.parse(text); if (validateProject(parsed)) { setProject(parsed); return; } const articleFile = parsed as { format?: string; version?: number; article?: Article }; if (articleFile.format === "cockipedia-article" && articleFile.version === 1 && articleFile.article && typeof articleFile.article.title === "string" && typeof articleFile.article.source === "string") { setProject({ format: "cockipedia-project", version: 1, exportedAt: new Date().toISOString(), articles: [articleFile.article], revisions: [], media: [], settings: [] }); return; } throw new Error("This is not a valid Cockipedia project or article file."); } catch (reason) { setError(reason instanceof Error ? reason.message : "The file could not be read."); } };
  const runImport = async () => { if (!file) return; setBusy(true); try { if (project) await importProject(project, strategy); else { const { createArticle } = await import("../lib/db"); await createArticle({ title: file.name.replace(/\.(txt|wiki|wikitext)$/i, "") || "Imported article", source: await file.text(), description: "Imported wikitext" }, "Imported article"); } await onChanged(); setFile(null); setProject(null); alert("Import complete."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Import failed."); } finally { setBusy(false); } };
  const exportFull = async () => { const data = await exportProject(); download(`cockipedia-backup-${new Date().toISOString().slice(0, 10)}.cockipedia`, JSON.stringify(data, null, 2), "application/vnd.cockipedia+json"); };
  if (mode === "import") return <div><PageHeader title="Import" description="Bring in a Cockipedia project or a wikitext article" /><div className="import-panel"><input ref={inputRef} hidden type="file" accept=".cockipedia,.json,.txt,.wiki,.wikitext" onChange={(event) => inspect(event.target.files?.[0] ?? null)} /><button className="file-drop" onClick={() => inputRef.current?.click()}><span>⇧</span><b>{file ? file.name : "Choose a project or article file"}</b><small>.cockipedia, .json, .txt, .wiki, or .wikitext</small></button>{error && <div className="error-box">{error}</div>}{project && <div className="import-summary"><b>Validated Cockipedia project</b><span>{project.articles.length} articles · {project.revisions.length} revisions · {project.media.length} media files</span><fieldset><legend>When a title already exists</legend><label><input type="radio" checked={strategy === "keep"} onChange={() => setStrategy("keep")} /> Keep the existing page</label><label><input type="radio" checked={strategy === "copy"} onChange={() => setStrategy("copy")} /> Import as a copy</label><label><input type="radio" checked={strategy === "overwrite"} onChange={() => setStrategy("overwrite")} /> Overwrite the existing page</label></fieldset></div>}<div className="modal-actions"><button className="primary" disabled={!file || !!error || busy} onClick={runImport}>{busy ? "Importing…" : "Import"}</button></div></div></div>;
  return <div><PageHeader title="Export" description="Download portable copies of your pages and local database" /><div className="export-options"><section><div className="export-icon">▣</div><div><h2>Export backup</h2><p>Download a complete <code>.cockipedia</code> project with articles, revision history, media, and settings.</p><button className="primary" onClick={exportFull}>Export full backup</button></div></section>{current && <section><div className="export-icon">≡</div><div><h2>Export “{current.title}”</h2><p>Download the current article in a format you can inspect or share.</p><div className="button-row"><button onClick={() => download(`${current.title}.json`, JSON.stringify({ format: "cockipedia-article", version: 1, article: current }, null, 2), "application/json")}>Article JSON</button><button onClick={() => download(`${current.title}.wikitext`, current.source, "text/plain")}>Wikitext</button><button onClick={() => { const rendered = parseWiki(current.source, articles, media); const title = current.title.replace(/[<>&]/g, ""); download(`${current.title}.html`, `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${title}</title><style>body{max-width:960px;margin:40px auto;padding:0 24px;color:#202122;font:16px/1.6 Georgia,serif}h1,h2{border-bottom:1px solid #a2a9b1}.infobox{float:right;width:280px;border:1px solid #a2a9b1;background:#f8f9fa;padding:8px;margin:0 0 20px 24px}.infobox table,.wikitable{border-collapse:collapse;width:100%}.infobox th,.infobox td,.wikitable th,.wikitable td{border:1px solid #a2a9b1;padding:6px;text-align:left}a{color:#36c}.wiki-image{max-width:320px}.wiki-image img{max-width:100%}@media(max-width:600px){.infobox{float:none;width:auto;margin:10px 0}}</style></head><body><article><h1>${title}</h1>${rendered.html}</article></body></html>`, "text/html"); }}>Standalone HTML</button></div></div></section>}</div></div>;
}

export function SettingsPage({ settings, trash, onSettings, onRestore, onRemove, onClear }: { settings: WikiSettings; trash: Article[]; onSettings: (value: WikiSettings) => void; onRestore: (article: Article) => void; onRemove: (article: Article) => void; onClear: () => void }) {
  return <div><PageHeader title="Settings" description="Appearance, storage, and recovery options for this device" /><section className="settings-section"><h2>Reading appearance</h2><div className="settings-grid"><Field label="Color"><select value={settings.theme} onChange={(event) => onSettings({ ...settings, theme: event.target.value as WikiSettings["theme"] })}><option value="light">Light</option><option value="dark">Dark</option><option value="auto">Automatic</option></select></Field><Field label="Text size"><select value={settings.textSize} onChange={(event) => onSettings({ ...settings, textSize: event.target.value as WikiSettings["textSize"] })}><option value="small">Small</option><option value="standard">Standard</option><option value="large">Large</option></select></Field><Field label="Article width"><select value={settings.width} onChange={(event) => onSettings({ ...settings, width: event.target.value as WikiSettings["width"] })}><option value="standard">Standard</option><option value="wide">Wide</option></select></Field></div></section><section className="settings-section"><h2>Recently deleted</h2><p>Deleted pages stay here until you remove them permanently.</p>{trash.length ? <div className="trash-list">{trash.map((article) => <div key={article.id}><div><b>{article.title}</b><span>Deleted {article.trashedAt && formatDate(article.trashedAt)}</span></div><button onClick={() => onRestore(article)}>Restore</button><button className="danger-text" onClick={() => onRemove(article)}>Delete permanently</button></div>)}</div> : <p className="muted">The recycle bin is empty.</p>}</section><section className="settings-section danger-zone"><h2>Reset Cockipedia</h2><p>Clears articles, revisions, media, and settings from this browser. Export a backup first.</p><button className="danger" onClick={onClear}>Clear all local data…</button></section></div>;
}

export function HistoryView({ article, revisions, onBack, onRestore }: { article: Article; revisions: Revision[]; onBack: () => void; onRestore: (revision: Revision) => void }) {
  const ordered = revisions.filter((revision) => revision.articleId === article.id).sort((a, b) => b.number - a.number); const [compare, setCompare] = useState<[number, number] | null>(ordered.length > 1 ? [ordered[1].number, ordered[0].number] : null); const [viewing, setViewing] = useState<Revision | null>(null);
  const oldRevision = compare ? ordered.find((revision) => revision.number === compare[0]) : undefined; const newRevision = compare ? ordered.find((revision) => revision.number === compare[1]) : undefined;
  return <div><PageHeader title={`Revision history of ${article.title}`} description={`${ordered.length} saved revision${ordered.length === 1 ? "" : "s"}`} /><button className="back-link" onClick={onBack}>← Return to article</button>{oldRevision && newRevision && <Diff oldText={oldRevision.source} newText={newRevision.source} oldLabel={`Revision ${oldRevision.number}`} newLabel={`Revision ${newRevision.number}`} />}{viewing && <div className="old-revision"><div><b>Revision {viewing.number}</b> from {formatDate(viewing.timestamp)}</div><pre>{viewing.source}</pre><button onClick={() => setViewing(null)}>Close revision</button></div>}<div className="history-list">{ordered.map((revision, index) => <div key={revision.id}><div className="history-dot" /><div><b>Revision {revision.number}</b> <span>{formatDate(revision.timestamp)}</span><p>{revision.summary} {revision.minor && <small>(minor edit)</small>}</p><small>{revision.source.length.toLocaleString()} bytes {index < ordered.length - 1 && `(${revision.source.length - ordered[index + 1].source.length >= 0 ? "+" : ""}${revision.source.length - ordered[index + 1].source.length})`}</small></div><div className="history-actions"><button onClick={() => setViewing(revision)}>View</button>{revision.number !== ordered[0]?.number && <><button onClick={() => setCompare([revision.number, ordered[0].number])}>Compare with current</button><button onClick={() => onRestore(revision)}>Restore</button></>}</div></div>)}</div></div>;
}

export function Diff({ oldText, newText, oldLabel = "Before", newLabel = "After" }: { oldText: string; newText: string; oldLabel?: string; newLabel?: string }) {
  const oldLines = oldText.split("\n"); const newLines = newText.split("\n"); const length = Math.max(oldLines.length, newLines.length);
  return <div className="diff"><div className="diff-head"><b>{oldLabel}</b><b>{newLabel}</b></div>{Array.from({ length }, (_, index) => { const oldLine = oldLines[index] ?? ""; const newLine = newLines[index] ?? ""; const changed = oldLine !== newLine; return <div className="diff-row" key={index}><pre className={changed ? "removed" : ""}>{oldLine || " "}</pre><pre className={changed ? "added" : ""}>{newLine || " "}</pre></div>; })}</div>;
}

export { download, formatDate };
